services:
  db:
    container_name: postgresql-db-mercadinho
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
          - data_db_mercadinho:/var/lib/postgresql/data
    networks:
      - mercadinho_network

  flask-api:
    depends_on:
      - db
    container_name: mercado
    build:
      context: .
      dockerfile: Dockerfile
    image: mercadinho-flask-api:3.0
    environment:
      DATABASE_URL: postgresql://postgres:admintesteh@postgresql-db-mercadinho:5432/postgres
    ports:
      - 8888:8888
    networks:
      - mercadinho_network

  frontend:
    depends_on:
      - flask-api
    container_name: mercado-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mercadinho-frontend:1.0
    ports:
      - 8081:80
    networks:
      - mercadinho_network

volumes:
  data_db_mercadinho:

networks:
  mercadinho_network:
    driver: bridge