services:
  db:
    container_name: postgresql-db-mercadinho
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
          - data_db_mercadinho:/var/lib/postgresql/data
    networks:
      - mercadinho_network

  flask-api:
    depends_on:
      - db
    container_name: mercado
    build:
      context: .
      dockerfile: Dockerfile
    image: mercadinho-flask-api:3.0
    environment:
      DATABASE_URL: postgresql://postgres:admintesteh@postgresql-db-mercadinho:5432/postgres
      # "postgresql://postgres:admintesteh@postgres-h.caisrwnnknl6.us-east-1.rds.amazonaws.com:5432/postgres"
    ports:
      - 8888:8888
    networks:
      - mercadinho_network

volumes:
  data_db_mercadinho:

networks:
  mercadinho_network:
    driver: bridge