apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: flask-api
  labels:
    app: flask-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: flask-api
          image: harbor.henrique.local/flask-api/mercadinho-flask-api:4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:admin@postgres:5432/postgres"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0