alloy:
  configMap:
    content: |
      discovery.kubernetes "all_pods" {
        role = "pod"
      }

      loki.relabel "filter_and_label" {
        forward_to = [loki.write.local_loki.receiver]

        // Regra 1: Mantem flask-api, monitoring e default (onde esta o postgres)
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "flask-api|monitoring|default"
          action        = "keep"
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_label_app"]
          target_label  = "app"
        }

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "job"
        }
      }

      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.all_pods.targets
        forward_to = [loki.relabel.filter_and_label.receiver]
      }

      loki.write "local_loki" {
        endpoint {
          url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
          batch_wait = "500ms"
          batch_size = "1024"
        }
      }
    create: true

  mounts:
    varlog: true

rbac:
  create: true
