mimir:
  structuredConfig:
    multitenancy_enabled: false
    ingester:
      ring:
        replication_factor: 1
    common:
      storage:
        backend: s3
        s3:
          endpoint: mimir-minio.monitoring.svc:9000
          access_key_id: mimir
          secret_access_key: supersecret
          insecure: true
          bucket_name: mimir

# Scale everything down to 1 pod for Minikube
ingester:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi
querier:
  replicas: 1
query_frontend:
  replicas: 1
distributor:
  replicas: 1
store_gateway:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi
compactor:
  replicas: 1
  persistence:
    enabled: true
    size: 2Gi

# Disable components for a minimal setup
alertmanager:
  enabled: false
ruler:
  enabled: false
overrides_exporter:
  enabled: false

# Enable Minio internally for simplicity in Minikube
minio:
  enabled: true
  replicas: 1
  rootUser: mimir
  rootPassword: supersecret
  persistence:
    enabled: true
    size: 5Gi
