apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-mercadinho
  namespace: argocd
data:
  password: Z2hwX2JaYnhQejJXeTEzM2xnRFNBaWFsQUpGQVlrMWI5SjNLT25WYg==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL0hlbnJpcXVlNzYyL21lcmNhZGluaG8uZ2l0
  username: Z2l0
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Henrique762/mercadinho.git
    path: manifests/argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: shared
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s