apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mercado-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Henrique762/mercadinho-infra.git
    path: manifests/flask-api
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-api
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
