apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-mercadinho
  namespace: argocd
data:
  password: Z2hwX2xIUENNY2FhdmQ2SDI5WkVGQjhHelF3OXBqVnNyMDQyOTJXbA==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL0hlbnJpcXVlNzYyL21lcmNhZGluaG8uZ2l0
  username: Z2l0
type: Opaque