adminPassword: admin
persistence:
  enabled: true
  size: 2Gi
service:
  type: ClusterIP

securityContext:
  fsGroup: 472
  runAsGroup: 472
  runAsUser: 472
initChownData:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      url: http://mimir-gateway.monitoring.svc:80/prometheus
      access: proxy
      isDefault: true
      jsonData:
        prometheusType: Mimir
        prometheusVersion: "2.4.0"
