expose:
  type: clusterIP
  clusterIP:
    name: harbor-expose
    ports:
      httpPort: 80
  tls:
    enabled: false

externalURL: https://harbor.henrique.local

# Otimizações para Homelab
harborAdminPassword: "Harbor12345"
persistence:
  enabled: true

# Configurações de banco de dados para resolver erros de permissão em Homelab
database:
  type: internal
  internal:
    # Init container para corrigir permissões de proprietário (UID 999 para Postgres)
    extrInitContainers:
      - name: fix-permissions
        image: busybox
        command: ["/bin/sh", "-c", "chown -R 999:999 /var/lib/postgresql/data && chmod -R 700 /var/lib/postgresql/data"]
        volumeMounts:
          - name: database-data
            mountPath: /var/lib/postgresql/data
    # Aumentando o tempo de espera do healthcheck para dar tempo ao initdb
    livenessProbe:
      initialDelaySeconds: 300
    readinessProbe:
      initialDelaySeconds: 10
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
redis:
  type: internal
  internal:
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 100m
