controller:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  componentName: "jenkins-controller"
  podSecurityContextOverride:
    runAsNonRoot: false
  customInitContainers:
    - name: fix-permissions
      image: "alpine:3"
      command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
  persistence:
    enabled: true
    size: "8Gi"
    storageClass: "standard"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.0
    - configuration-as-code:2053.vb_0da_47381a_25
persistence:
  enabled: true
  size: 8Gi

