monitoringPasscode: "define_it"

community:
  enabled: true

jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://postgres.flask-api:5432/sonar"
  jdbcUsername: "postgres"
  jdbcPassword: "admin"

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 800Mi

sonarProperties:
  sonar.web.javaOpts: "-Xmx256m -Xms256m -XX:+UseSerialGC"
  sonar.search.javaOpts: "-Xmx128m -Xms128m -XX:MaxDirectMemorySize=32m"
  sonar.ce.javaOpts: "-Xmx128m -Xms128m -XX:+UseSerialGC"

startupProbe:
  failureThreshold: 60
