image:
  tag: 9.9.8-community

monitoringPasscode: "define_it"

postgresql:
  enabled: false

jdbcOverwrite:
  enable: true
  jdbcUrl: "jdbc:postgresql://postgres.flask-api:5432/postgres"
  jdbcUsername: "postgres"
  jdbcPassword: "admin"

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 800m
    memory: 1.5Gi

sonarProperties:
  sonar.web.javaOpts: "-Xmx384m -Xms384m -XX:+UseSerialGC"
  sonar.search.javaOpts: "-Xmx256m -Xms256m -XX:MaxDirectMemorySize=64m"
  sonar.ce.javaOpts: "-Xmx256m -Xms256m -XX:+UseSerialGC"

hostAliases:
  - ip: "127.0.0.1"
    hostnames:
      - "off"

startupProbe:
  failureThreshold: 60

