name: CI-CD Mercado
on: [push]

env:
  ECS_CLUSTER: "1"
  ECS_TASK_DEFINITION: "1"
  ECR: "1"
  END_DB: ""

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        run: |
          ls -l

      - name: BUILD DOCKER & PUSH ECR
        uses: docker://ghcr.io/kciter/aws-ecr-action:latest
        with:
          access_key_id: ${{ secrets.aws-access-key-id }}
          secret_access_key: ${{ secrets.aws-secret-access-key }}
          account_id: ${{ inputs.account_id }}
          repo: ${{ inputs.env }}-${{ inputs.kube_service }}.${{ inputs.dominio }}
          region: us-east-1
          tags: ${{ github.run_number }}
          create_repo: true
          dockerfile: checkout/${{ inputs.git_d }}
          path: checkout/src/
        
      
  


  

